name: Azure Static Web Apps CI/CD - Backend

on:
  push:
    branches:
      - prod
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - prod

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install dependencies
        run: |
          cd Semana7/jsonserver
          npm ci
      - name: Build frontend
        run: |
          cd Semana7/jsonserver
          npm run build || echo "No build script found, skipping."
      - name: Start json-server backend
        run: |
          cd Semana7/jsonserver
          npm run start:server &
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_SKY_0158CA21E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: Semana7/jsonserver # App source code path
          api_location: null # Api source code path - optional
          output_location: . # No build output, use current directory
          app_build_command: npm run build # Explicitly run the build script

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_SKY_0158CA21E }}
          action: "close"
